a = int(input("Enter a value: "))
print("You entered:", a)
# print("THE TYPE OF A:", type(a))
b =int(input("Enter b value: "))
print("You entered:", b)
print("the sum of valure a and b is:", a + b)
c =("hello")
d =(input("enter your name: ") )
print("greeting message:", c + " " + d)